blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog import views as v
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(v.BlogEntryListView.as_view()), name='blogentry_list'),
    # path('blog/create', v.BlogEntryCreateView.as_view(), name='create_blog_entry'),
    path('view/<slug:slug>', v.BlogEntryDetailView.as_view(), name='view_blog_entry'),
    # path('update/<slug:slug>', v.BlogEntryUpdateView.as_view(), name='update_blog_entry'),
    # path('delete/<slug:slug>', v.BlogEntryDeleteView.as_view(), name='delete_blog_entry'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from config import settings
from mailing_management_service.views import HomeView
from users.views import ModeratorInterfaceView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('moderator/', ModeratorInterfaceView.as_view(), name='moderator_interface'),

    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('users.urls', namespace='user')),
    path('mms/', include('mailing_management_service.urls', namespace='mms')),
    path('', cache_page(60)(HomeView.as_view()), name='main'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_management_service/urls.py
from django.urls import path

from mailing_management_service import views as v
from mailing_management_service.apps import MailingManagementServiceConfig

app_name = MailingManagementServiceConfig.name

urlpatterns = [
    path('', v.MailingListView.as_view(), name='mailing_list'),
    path('create/', v.MailingCreateView.as_view(), name='create_mailing'),
    path('view/<int:pk>', v.MailingDetailView.as_view(), name='view_mailing'),
    path('view/<int:pk>/mailinglog', v.MailingLogListView.as_view(), name='view_mailinglog'),
    path('update/<int:pk>', v.MailingUpdateView.as_view(), name='update_mailing'),
    path('delete/<int:pk>', v.MailingDeleteView.as_view(), name='delete_mailing'),

    path('change_mailing_letter/<int:pk>/', v.change_letter_view, name='change_mailing_letter'),
    path('change_is_launched/<int:pk>/', v.change_is_launched_view, name='change_is_launched'),

    path('letters/', v.LetterListView.as_view(), name='letter_list'),
    path('letters/create/', v.LetterCreateView.as_view(), name='create_letter'),
    path('letters/view/<int:pk>', v.LetterDetailView.as_view(), name='view_letter'),
    path('letters/update/<int:pk>', v.LetterUpdateView.as_view(), name='update_letter'),
    path('letters/delete/<int:pk>', v.LetterDeleteView.as_view(), name='delete_letter'),

    path('recipients/', v.RecipientListView.as_view(), name='recipient_list'),
    path('recipients/create/', v.RecipientCreateView.as_view(), name='create_recipient'),
    path('recipients/view/<int:pk>', v.RecipientDetailView.as_view(), name='view_recipient'),
    path('recipients/update/<int:pk>', v.RecipientUpdateView.as_view(), name='update_recipient'),
    path('recipients/delete/<int:pk>', v.RecipientDeleteView.as_view(), name='delete_recipient'),
]

mailing_management_service/models.py
from django.db import models

from users.models import User


class Recipient(models.Model):
    email = models.EmailField(verbose_name='Почта', unique=True)
    is_active = models.BooleanField(verbose_name='Активный', default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец получателей', blank=True)

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'Получатель'
        verbose_name_plural = 'Получатели'


class Letter(models.Model):
    subject = models.CharField(max_length=100, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец рассылки', blank=True, null=True)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Письмо рассылки'
        verbose_name_plural = 'Письма рассылки'


class Mailing(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название рассылки')
    description = models.CharField(max_length=150, verbose_name='Описание рассылки', blank=True, null=True)
    time = models.TimeField(verbose_name='Время рассылки')
    periodicity = models.IntegerField(verbose_name='Периодичность рассылки',
                                      choices=((1, 'Ежедневно'), (7, 'Еженедельно'), (30, 'Ежемесячно')))
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец рассылки', blank=True, null=True)
    is_launched = models.BooleanField(default=False, verbose_name='Запущена')
    letter = models.ForeignKey(Letter, on_delete=models.CASCADE, verbose_name='Письмо рассылки', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')
    recipients = models.ManyToManyField(Recipient, blank=True, verbose_name='Получатели')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            (
                'deactivate_mailing',
                'Can deactivate mailing'
            ),
        ]


class MailingLog(models.Model):
    last_time = models.DateTimeField(verbose_name='Время рассылки')
    status = models.BooleanField(verbose_name='Статус последней рассылки')
    server_answer = models.TextField(verbose_name='Ответ почтового сервера', blank=True, null=True)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Письмо рассылки', blank=True,
                                null=True)

    def __str__(self):
        return f'{self.last_time} {self.status}'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылки'

mailing_management_service/forms.py
from django import forms

from mailing_management_service import models as m


class MailingForm(forms.ModelForm):
    class Meta:
        model = m.Mailing
        fields = '__all__'
        exclude = ('is_launched', 'user',)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'
        letter_choices = m.Letter.objects.filter(user=user).values_list('pk', 'subject')
        self.fields['letter'].widget.choices = letter_choices


class LetterForm(forms.ModelForm):
    class Meta:
        model = m.Letter
        fields = '__all__'
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class LetterChoiceForm(forms.ModelForm):
    class Meta:
        model = m.Mailing
        fields = ('letter',)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'
        letter_choices = m.Letter.objects.filter(user=user).values_list('pk', 'subject')
        self.fields['letter'].widget.choices = letter_choices


class RecipientForm(forms.ModelForm):
    class Meta:
        model = m.Recipient
        fields = '__all__'
        exclude = ('user', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

mailing_management_service/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic as g

from mailing_management_service import forms as f
from mailing_management_service import models as m
from mailing_management_service import services
from users.models import User


class MailingListView(LoginRequiredMixin, g.ListView):
    model = m.Mailing
    ordering = ['-created_at']

    def get_queryset(self):
        queryset = super().get_queryset().filter(user=self.request.user)
        return queryset


class MailingCreateView(LoginRequiredMixin, g.CreateView):
    model = m.Mailing
    success_url = reverse_lazy('mms:mailing_list')
    form_class = f.MailingForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        mailing = form.save(commit=False)
        mailing.user = self.request.user
        mailing.save()
        return super().form_valid(form=form)


class MailingUpdateView(LoginRequiredMixin, g.UpdateView):
    model = m.Mailing
    form_class = f.MailingForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['instance'] = self.object
        return kwargs

    def get(self, request, *args, **kwargs):
        if services.is_creator(self.request.user, m.Mailing.objects.get(pk=kwargs.get('pk'))):
            return super().get(request)
        return HttpResponseForbidden("Доступ запрещен")

    def form_valid(self, form):
        if services.is_creator(self.request.user, self.object):
            response = super().form_valid(form)
            services.update_cron_task_mailing(self.object)
            return response
        return HttpResponseForbidden("Доступ запрещен")

    def get_success_url(self):
        return reverse_lazy('mms:view_mailing', kwargs={'pk': self.object.pk})


class MailingDetailView(LoginRequiredMixin, g.DetailView):
    model = m.Mailing


class MailingDeleteView(LoginRequiredMixin, g.DeleteView):
    model = m.Mailing
    success_url = reverse_lazy('mms:mailing_list')

    def get(self, request, *args, **kwargs):
        if services.is_creator(self.request.user, m.Mailing.objects.get(pk=kwargs.get('pk'))):
            return super().get(request)
        return HttpResponseForbidden("Доступ запрещен")

    def form_valid(self, form):
        if services.is_creator(self.request.user, self.object):
            return super().form_valid(form)
        return HttpResponseForbidden("Доступ запрещен")


def change_letter_view(request, pk):
    letter_pk = request.POST.get('letter')
    if letter_pk:
        letter = m.Letter.objects.get(pk=letter_pk)
    else:
        letter = None
    mailing = m.Mailing.objects.get(pk=pk)
    mailing.letter = letter
    mailing.save()
    return redirect(to=reverse_lazy('mms:mailing_list'))


def change_is_launched_view(request, pk):
    mailing = m.Mailing.objects.get(pk=pk)
    if services.is_moderator_or_creator(request.user, mailing):
        if mailing.is_launched:
            mailing.is_launched = False
            services.remove_cron_task_mailing(mailing)
        else:
            mailing.is_launched = True
            services.add_cron_task_mailing(mailing)
        mailing.save()
        return redirect(to=request.META.get('HTTP_REFERER', reverse_lazy('mms:mailing_list')))
    else:
        return HttpResponseForbidden("Доступ запрещен")


class LetterCreateView(LoginRequiredMixin, g.CreateView):
    model = m.Letter
    success_url = reverse_lazy('mms:letter_list')
    form_class = f.LetterForm

    def form_valid(self, form):
        letter = form.save(commit=False)
        letter.user = self.request.user
        letter.save()
        return super().form_valid(form=form)


class LetterListView(LoginRequiredMixin, g.ListView):
    model = m.Letter

    def get_queryset(self):
        queryset = super().get_queryset().filter(user=self.request.user)
        return queryset


class LetterDetailView(LoginRequiredMixin, g.DetailView):
    model = m.Letter


class LetterUpdateView(LoginRequiredMixin, g.UpdateView):
    model = m.Letter
    form_class = f.LetterForm

    def get(self, request, *args, **kwargs):
        if services.is_creator(self.request.user, m.Letter.objects.get(pk=kwargs.get('pk'))):
            return super().get(request)
        return HttpResponseForbidden("Доступ запрещен")

    def get_success_url(self):
        return reverse_lazy('mms:view_letter', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        if services.is_creator(self.request.user, self.object):
            return super().form_valid(form)
        return HttpResponseForbidden("Доступ запрещен")


class LetterDeleteView(LoginRequiredMixin, g.DeleteView):
    model = m.Letter
    success_url = reverse_lazy('mms:letter_list')

    def get(self, request, *args, **kwargs):
        if services.is_creator(self.request.user, m.Letter.objects.get(pk=kwargs.get('pk'))):
            return super().get(request)
        return HttpResponseForbidden("Доступ запрещен")

    def form_valid(self, form):
        if services.is_creator(self.request.user, self.object):
            return super().form_valid(form)
        return HttpResponseForbidden("Доступ запрещен")


class MailingLogListView(g.ListView):
    model = m.MailingLog
    ordering = ['-last_time']

    def get_queryset(self):
        return super().get_queryset().filter(mailing=m.Mailing.objects.get(pk=self.kwargs.get('pk')))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing'] = m.Mailing.objects.get(pk=self.kwargs.get('pk'))
        return context


class HomeView(g.View):
    def get(self, request):
        context = {
            'mailing': len(m.Mailing.objects.all()),
            'mailing_active': len(m.Mailing.objects.filter(is_launched=True)),
            'users': len(User.objects.filter(is_active=True)),
        }
        return render(request, template_name='main.html', context=context)


class RecipientCreateView(LoginRequiredMixin, g.CreateView):
    model = m.Recipient
    success_url = reverse_lazy('mms:recipient_list')
    form_class = f.RecipientForm

    def form_valid(self, form):
        letter = form.save(commit=False)
        letter.user = self.request.user
        letter.save()
        return super().form_valid(form=form)


class RecipientListView(LoginRequiredMixin, g.ListView):
    model = m.Recipient

    def get_queryset(self):
        queryset = super().get_queryset().filter(user=self.request.user)
        return queryset


class RecipientDetailView(LoginRequiredMixin, g.DetailView):
    model = m.Recipient


class RecipientUpdateView(LoginRequiredMixin, g.UpdateView):
    model = m.Recipient
    form_class = f.RecipientForm

    def get(self, request, *args, **kwargs):
        if services.is_creator(self.request.user, m.Recipient.objects.get(pk=kwargs.get('pk'))):
            return super().get(request)
        return HttpResponseForbidden("Доступ запрещен")

    def get_success_url(self):
        return reverse_lazy('mms:view_recipient', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        if services.is_creator(self.request.user, self.object):
            return super().form_valid(form)
        return HttpResponseForbidden("Доступ запрещен")


class RecipientDeleteView(LoginRequiredMixin, g.DeleteView):
    model = m.Recipient
    success_url = reverse_lazy('mms:recipient_list')

    def get(self, request, *args, **kwargs):
        if services.is_creator(self.request.user, m.Recipient.objects.get(pk=kwargs.get('pk'))):
            return super().get(request)
        return HttpResponseForbidden("Доступ запрещен")

    def form_valid(self, form):
        if services.is_creator(self.request.user, self.object):
            return super().form_valid(form)
        return HttpResponseForbidden("Доступ запрещен")

mailing_management_service/templates/mailing_management_service/letter_detail.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
    <h2 class="pb-2 border-bottom text-center">Письмо: "{{ object.subject|title }}"</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-1 text-center">
        <div class="feature col">
            <h3 class="fs-2 text-body-emphasis">Текст: </h3>
            <p>{{ object.body }}</p>
        </div>
    </div>
    <div class="row justify-content-md-center align-items-center">
        <div class="col-auto">
            <a href="javascript:history.go(-1);" class="btn btn-primary">Назад</a>
        </div>
        <div class="col-auto">
            <a href="{% url 'mms:update_letter' pk=object.pk %}" class="btn btn-primary profile-button"
               type="submit">Изменить</a>
        </div>
{% endblock %}

mailing_management_service/templates/mailing_management_service/letter_form.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
    {% url 'mms:create_letter' as create_letter %}

    <div class="text-center">
        <div>
            <h1 class="mt-4">
                {% if request.path == create_letter %}
                    <a href="{% url 'mms:create_mailing' %}">СОЗДАНИЕ РАССЫЛКИ</a> | СОЗДАНИЕ ПИСЬМА<br>
                    <a href="{% url 'mms:create_recipient' %}">ДОБАВИТЬ ПОЛУЧАТЕЛЯ</a>
                {% else %}
                    ИЗМЕНЕНИЕ ПИСЬМА
                {% endif %}
            </h1>
        </div>
    </div>
    <div class="p-3 py-5">
        <div class="col-3 mt-2 mx-auto">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        <div class="text-danger">
                            <p>{{ field.errors }}</p>
                        </div>
                    {% endif %}
                    <br>
                {% endfor %}
                <div class="row justify-content-md-center">
                    <div class="col-auto align-items-center">
                        <a href="javascript:history.go(-1);" class="btn btn-primary">Назад</a>
                    </div>
                    <div class="col-auto align-items-center">
                        <button class="btn btn-primary profile-button" type="submit">
                            Сохранить
                        </button>
                    </div>
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger mt-5 ">
                            <p>{{ form.non_field_errors }}</p>
                        </div>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
    <script>
        const csrf_token = "{{ csrf_token }}"; // Получаем значение CSRF-токена из контекста Django
    </script>
    <script src="{% static 'js/change_avatar_script.js' %}"></script>
{% endblock %}

mailing_management_service/templates/mailing_management_service/letter_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
    <h1 class="mb-4 text-center">Мои письма
        <a href="{% url 'mms:create_letter' %}" class="btn btn-outline-primary">+</a></h1>
    <div class="row align-items-center justify-content-center">
        {% for object in object_list %}
            <div class="col-4 d-flex flex-column flex-lg-row align-items-center p-3 rounded-3 shadow-lg m-3"
                 data-bs-theme="light">
                <div class="col align-items-center justify-content-center text-center">
                    <a href="#">
                        <div class="p-3 btn btn-hover-light rounded-2 align-items-center gap-2 py-2 px-3 lh-sm">
                            <h1 class="d-block mb-1 fs-4 text-break text-center">{{ object.subject|truncatechars:20 }}</h1>
                            <small class="text-break text-center">{{ object.body|truncatechars:50 }}</small>
                        </div>
                    </a>
                </div>
                <div class="d-none d-lg-block vr mx-4 opacity-10">&nbsp;</div>
                <hr class="d-lg-none">
                <div class="col-auto pe-3">
                    <nav>
                        <ul class="d-flex flex-column gap-2 list-unstyled small">
                            <li><a href="{% url 'mms:view_letter' pk=object.pk%}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Посмотреть</a>
                            </li>
                            <li><a href="{% url 'mms:update_letter' pk=object.pk%}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Изменить</a>
                            </li>
                            <li><a href="{% url 'mms:delete_letter' pk=object.pk%}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Удалить</a>
                            </li>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mailing_management_service/templates/mailing_management_service/mailing_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
    <h1 class="mb-4 text-center">Мои рассылки
        <a href="{% url 'mms:create_mailing' %}" class="btn btn-outline-primary">+</a></h1>
    <div class="row align-items-center justify-content-center">
        {% for object in object_list %}
            <div class="col-4 d-flex flex-column flex-lg-row align-items-center p-3 rounded-3 shadow-lg m-3"
                 data-bs-theme="light">
                <div class="col align-items-center justify-content-center text-center">
                    <a href="#">
                        <div class="p-3 btn btn-hover-light rounded-2 align-items-center gap-2 py-2 px-3 lh-sm">
                            <h1 class="d-block mb-1 fs-4 text-break text-center">{{ object.name|truncatechars:20 }}</h1>
                            <small class="text-break text-center">{{ object.description|truncatechars:50 }}</small>
                            <hr>
                            <div>
                                <form method="post"
                                      action="{% url 'mms:change_mailing_letter' pk=object.pk %}">
                                    {% csrf_token %}
                                    {% get_letter_form object.pk user as letter_form %}
                                    {% for field in letter_form %}
                                        <div class="mb-2">{{ field.label_tag }}</div>
                                        <div class="mb-2">{{ field }}</div>
                                    {% endfor %}
                                    <input class="btn btn-primary" type="submit" value="Изменить">
                                </form>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="d-none d-lg-block vr mx-4 opacity-10">&nbsp;</div>
                <hr class="d-lg-none">
                <div class="col-auto pe-3">
                    <nav>
                        <ul class="d-flex flex-column gap-2 list-unstyled small">
                            <li><a href="{% url 'mms:view_mailing' pk=object.pk %}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Посмотреть</a>
                            </li>
                            <li><a href="{% url 'mms:update_mailing' pk=object.pk %}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Изменить</a>
                            </li>
                            <li><a href="{% url 'mms:delete_mailing' pk=object.pk %}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Удалить</a>
                            </li>
                            <li><a href="{% url 'mms:view_mailinglog' pk=object.pk %}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Логи</a>
                            </li>
                            {% if object.is_launched %}
                                <li><a href="{% url 'mms:change_is_launched' pk=object.pk %}"
                                       class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover text-danger">
                                    Остановить</a>
                                </li>
                            {% else %}
                                <li><a href="{% url 'mms:change_is_launched' pk=object.pk %}"
                                       class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover text-success">
                                    Запустить</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mailing_management_service/templates/mailing_management_service/recipient_detail.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
    <h2 class="pb-2 border-bottom text-center">Получатель: "{{ object.email }}"</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-1 text-center">
    </div>
    <div class="row justify-content-md-center align-items-center">
        <div class="col-auto">
            <a href="javascript:history.go(-1);" class="btn btn-primary">Назад</a>
        </div>
        <div class="col-auto">
            <a href="{% url 'mms:update_recipient' pk=object.pk %}" class="btn btn-primary profile-button"
               type="submit">Изменить</a>
        </div>
{% endblock %}

mailing_management_service/templates/mailing_management_service/recipient_form.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
    {% url 'mms:create_recipient' as create_recipient %}

    <div class="text-center">
        <div>
            <h1 class="mt-4">
                {% if request.path == create_recipient %}
                    <a href="{% url 'mms:create_mailing' %}">СОЗДАНИЕ РАССЫЛКИ</a> |
                    <a href="{% url 'mms:create_letter' %}">СОЗДАНИЕ ПИСЬМА</a> <br> ДОБАВИТЬ ПОЛУЧАТЕЛЯ
                {% else %}
                    ИЗМЕНЕНИЕ ПОЛУЧАТЕЛЯ
                {% endif %}
            </h1>
        </div>
    </div>
    <div class="p-3 py-5">
        <div class="col-3 mt-2 mx-auto">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        <div class="text-danger">
                            <p>{{ field.errors }}</p>
                        </div>
                    {% endif %}
                    <br>
                {% endfor %}
                <div class="row justify-content-md-center">
                    <div class="col-auto align-items-center">
                        <a href="javascript:history.go(-1);" class="btn btn-primary">Назад</a>
                    </div>
                    <div class="col-auto align-items-center">
                        <button class="btn btn-primary profile-button" type="submit">
                            Сохранить
                        </button>
                    </div>
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger mt-5 ">
                            <p>{{ form.non_field_errors }}</p>
                        </div>
                    {% endif %}
                </div>
            </form>
        </div>

    </div>
    <script>
        const csrf_token = "{{ csrf_token }}"; // Получаем значение CSRF-токена из контекста Django
    </script>
    <script src="{% static 'js/change_avatar_script.js' %}"></script>
{% endblock %}

mailing_management_service/templates/mailing_management_service/recipient_list.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
    <h1 class="mb-4 text-center">Мои получатели
        <a href="{% url 'mms:create_recipient' %}" class="btn btn-outline-primary">+</a></h1>
    <div class="row align-items-center justify-content-center">
        {% for object in object_list %}
            <div class="col-4 d-flex flex-column flex-lg-row align-items-center p-3 rounded-3 shadow-lg m-3"
                 data-bs-theme="light">
                <div class="col align-items-center justify-content-center text-center">
                    <a href="#">
                        <div class="p-3 btn btn-hover-light rounded-2 align-items-center gap-2 py-2 px-3 lh-sm">
                            <h2 class="d-block mb-1 fs-5 text-break text-center">{{ object.email|truncatechars:20 }}</h2>
                        </div>
                    </a>
                </div>
                <div class="d-none d-lg-block vr mx-4 opacity-10">&nbsp;</div>
                <hr class="d-lg-none">
                <div class="col-auto pe-3">
                    <nav>
                        <ul class="d-flex flex-column gap-2 list-unstyled small">
                            <li><a href="{% url 'mms:view_recipient' pk=object.pk %}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Посмотреть</a>
                            </li>
                            <li><a href="{% url 'mms:update_recipient' pk=object.pk %}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Изменить</a>
                            </li>
                            <li><a href="{% url 'mms:delete_recipient' pk=object.pk %}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Удалить</a>
                            </li>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}