blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog import views as v
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(v.BlogEntryListView.as_view()), name='blogentry_list'),
    # path('blog/create', v.BlogEntryCreateView.as_view(), name='create_blog_entry'),
    path('view/<slug:slug>', v.BlogEntryDetailView.as_view(), name='view_blog_entry'),
    # path('update/<slug:slug>', v.BlogEntryUpdateView.as_view(), name='update_blog_entry'),
    # path('delete/<slug:slug>', v.BlogEntryDeleteView.as_view(), name='delete_blog_entry'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from config import settings
from mailing_management_service.views import HomeView
from users.views import ModeratorInterfaceView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('moderator/', ModeratorInterfaceView.as_view(), name='moderator_interface'),

    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('users.urls', namespace='user')),
    path('mms/', include('mailing_management_service.urls', namespace='mms')),
    path('', cache_page(60)(HomeView.as_view()), name='main'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_management_service/urls.py
from django.urls import path

from mailing_management_service import views as v
from mailing_management_service.apps import MailingManagementServiceConfig

app_name = MailingManagementServiceConfig.name

urlpatterns = [
    path('', v.MailingListView.as_view(), name='mailing_list'),
    path('create/', v.MailingCreateView.as_view(), name='create_mailing'),
    path('view/<int:pk>', v.MailingDetailView.as_view(), name='view_mailing'),
    path('view/<int:pk>/mailinglog', v.MailingLogListView.as_view(), name='view_mailinglog'),
    path('update/<int:pk>', v.MailingUpdateView.as_view(), name='update_mailing'),
    path('delete/<int:pk>', v.MailingDeleteView.as_view(), name='delete_mailing'),

    path('change_mailing_letter/<int:pk>/', v.change_letter_view, name='change_mailing_letter'),
    path('change_is_launched/<int:pk>/', v.change_is_launched_view, name='change_is_launched'),

    path('letters/', v.LetterListView.as_view(), name='letter_list'),
    path('letters/create/', v.LetterCreateView.as_view(), name='create_letter'),
    path('letters/view/<int:pk>', v.LetterDetailView.as_view(), name='view_letter'),
    path('letters/update/<int:pk>', v.LetterUpdateView.as_view(), name='update_letter'),
    path('letters/delete/<int:pk>', v.LetterDeleteView.as_view(), name='delete_letter'),

    path('recipients/', v.RecipientListView.as_view(), name='recipient_list'),
    path('recipients/create/', v.RecipientCreateView.as_view(), name='create_recipient'),
    path('recipients/view/<int:pk>', v.RecipientDetailView.as_view(), name='view_recipient'),
    path('recipients/update/<int:pk>', v.RecipientUpdateView.as_view(), name='update_recipient'),
    path('recipients/delete/<int:pk>', v.RecipientDeleteView.as_view(), name='delete_recipient'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetView
from django.urls import path

from users import views as v
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('profile/', v.UserUpdateView.as_view(), name='profile'),
    path('profile/change-avatar/', v.change_avatar, name='change_avatar'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', v.UserLoginView.as_view(template_name='users/user_form.html'), name='login'),
    path('register/', v.RegisterView.as_view(), name='register'),
    path('verify_email/<str:token>/', v.VerifyEmailView.as_view(), name='verify_email'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('confirm_password_reset/<str:token>/', v.ConfirmPasswordResetView.as_view(), name='confirm_reset_password'),
    path('change_active_user/<int:pk>/', v.change_active_user_view, name='change_active_user'),
]

users/models.py
from django.apps import apps
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.db import models


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


def user_avatar_path(instance, filename):
    # Используйте email пользователя как часть пути загрузки
    return f'users/{instance.email}/{filename}'


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name='Почта', unique=True)
    comment = models.CharField(max_length=150, verbose_name='Комментарий', blank=True, null=True)
    email_verified = models.BooleanField(default=False, verbose_name='Почта подтверждена')
    email_verification_token = models.CharField(max_length=255, blank=True, null=True)
    avatar = models.ImageField(upload_to=user_avatar_path, verbose_name='Аватар', blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            (
                'deactivate_user',
                'Can deactivate user'
            ),
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm

from users.models import User


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password')  # Убираем поле пароля из формы
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar', 'password1', 'password2')

        # Меняем поля, так как исходная форма UserCreationForm
        # ссылается на поле username

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class UserAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ResetPasswordForm(forms.Form):
    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.fields.get('password'):
            self.fields.pop('password')  # Убираем поле пароля из формы
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

users/views.py
import os
import random
import string

from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Group
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.http import JsonResponse, HttpResponse, HttpResponseForbidden
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic as g

from config import settings
from mailing_management_service.models import Mailing
from users.forms import UserProfileForm, UserAuthenticationForm, RegisterForm
from users.models import User


class UserUpdateView(g.UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('user:profil')

    def get_object(self, queryset=None):
        return self.request.user


def change_avatar(request):
    if request.method == "POST" and request.FILES.get("avatar"):
        user = request.user
        try:
            old_avatar = os.path.join(settings.MEDIA_ROOT, f'{user.avatar}')
            os.remove(old_avatar)
        finally:
            user.avatar = request.FILES["avatar"]
            user.save()
            return JsonResponse({"message": "Аватар успешно обновлен!"})
    return JsonResponse({"error": "Произошла ошибка при обновлении аватара."}, status=400)


class UserLoginView(LoginView):
    form_class = UserAuthenticationForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to=reverse_lazy('user:profile'))
        else:
            return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        user = User.objects.get(email=form.cleaned_data.get('username'))
        if user.email_verified:
            return super().form_valid(form)
        else:
            form.add_error('username', 'Нужно подтвердить почту')
            return self.form_invalid(form)


class RegisterView(g.CreateView):
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('user:login')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to=reverse_lazy('user:profile'))
        else:
            return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        response = super().form_valid(form)
        new_user = form.save()
        if not new_user.avatar:
            new_user.avatar = 'users/user.png'
        # Создаем и сохраняем токен подтверждения
        token = ''.join(random.choices(string.ascii_letters + string.digits, k=50))
        new_user.email_verification_token = token
        new_user.save()
        # Отправляем письмо с подтверждением
        current_site = get_current_site(self.request)
        mail_subject = ('Подтвердите ваш аккаунт. '
                        'Пройдите по этой ссылке для подтверждения регистрации:')
        message = render_to_string(
            'users/email_verified.html',
            {
                'domain': current_site.domain,
                'token': token,
            },
        )
        send_mail(mail_subject, message, os.getenv('EMAIL_HOST_USER'), [new_user.email])
        return response


class VerifyEmailView(g.View):
    def get(self, request, token):
        try:
            user = User.objects.get(email_verification_token=token)
            user.email_verified = True
            user.save()
            return redirect('user:login')  # Редирект на страницу входа
        except User.DoesNotExist:
            return HttpResponse('Неверная ссылка подтверждения.')


class ConfirmPasswordResetView(g.View):
    def get(self, request, token):
        user = User.objects.get(email_verification_token=token)
        new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        user.set_password(new_password)
        user.save()
        return render(request, 'users/confirm_password_reset.html',
                      {'new_password': new_password})


class ModeratorInterfaceView(g.View):
    def get(self, request):
        moderators = Group.objects.get(name="moderators").user_set.all()
        if self.request.user not in moderators:
            return HttpResponseForbidden("Доступ запрещен")
        users = User.objects.all().order_by('-date_joined')
        mailings = Mailing.objects.all().order_by('-created_at')
        context = {
            'users': users,
            'mailings': mailings
        }
        return render(request, 'users/moderator_interface.html', context=context)


@permission_required('user.deactivate_user')
def change_active_user_view(request, pk):
    user = User.objects.get(pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True
    user.save()
    return redirect(reverse_lazy('moderator_interface'))

users/templates/users/confirm_password_reset.html
{% extends 'base.html' %}

{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Сброс пароля</h1>
        <p class="fs-5 text-body-secondary">Ваш новый пароль: {{ new_password }}</p>
    </div>
{% endblock %}

users/templates/users/email_verified.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Verification Successful</title>
</head>
<body>
<div class="text-center">
    {% csrf_token %}
    <h3 class="card-title">Подтвердите вашу электронную почту</h3>
    <p>Поздравляем, Вы зарегистрировались на нашем портале!</p>
    <p>Для завершения регистрации и подтверждения вашей электронной почты, пожалуйста, кликните по следующей ссылке:</p>
    <p><a href="{{ domain }}{% url 'user:verify_email' token=token %}">Подтвердить электронную почту</a></p>
</div>
</body>
</html>

users/templates/users/moderator_interface.html
{% extends 'base.html' %}
{% load my_tags %}
{% block content %}
    <h1 class="mb-4 text-center">Рассылки</h1>
    <div class="row align-items-center justify-content-center mb-5">
        {% for object in mailings %}
            <div class="col-4 d-flex flex-column flex-lg-row align-items-center p-3 rounded-3 shadow-lg m-3"
                 data-bs-theme="light">
                <div class="col align-items-center justify-content-center text-center">
                    <a href="#">
                        <div class="p-3 btn btn-hover-light rounded-2 align-items-center gap-2 py-2 px-3 lh-sm">
                            <h1 class="d-block mb-1 fs-4 text-break text-center">{{ object.name|truncatechars:20 }}</h1>
                            <small class="text-break text-center">{{ object.description|truncatechars:50 }}</small>
                        </div>
                    </a>
                </div>
                <div class="d-none d-lg-block vr mx-4 opacity-10">&nbsp;</div>
                <hr class="d-lg-none">
                <div class="col-auto pe-3">
                    <nav>
                        <ul class="d-flex flex-column gap-2 list-unstyled small">
                            <li><a href="{% url 'mms:view_mailing' pk=object.pk %}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Посмотреть</a>
                            </li>
                            <li><a href="{% url 'mms:view_mailinglog' pk=object.pk %}"
                                   class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">Логи</a>
                            </li>
                            {% if object.is_launched %}
                                <li><a href="{% url 'mms:change_is_launched' pk=object.pk %}"
                                       class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover text-danger">
                                    Остановить</a>
                                </li>
                            {% else %}
                                <li><a href="{% url 'mms:change_is_launched' pk=object.pk %}"
                                       class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover text-success">
                                    Запустить</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        {% endfor %}
    </div>
    <h1 class="mb-4 text-center">Пользователи</h1>
    <div class="row align-items-center justify-content-center">
        {% for object in users %}
            <div class="col-4 d-flex flex-column flex-lg-row align-items-center p-3 rounded-3 shadow-lg m-3"
                 data-bs-theme="light">
                <div class="col align-items-center justify-content-center text-center">
                    <a href="#">
                        <div class="p-3 btn btn-hover-light rounded-2 align-items-center gap-2 py-2 px-3 lh-sm">
                            <h1 class="d-block mb-1 fs-4 text-break text-center">{{ object.first_name }} {{ object.last_name }}</h1>
                            <small class="text-break text-center">{{ object.email }}</small>
                        </div>
                    </a>
                </div>
                <div class="d-none d-lg-block vr mx-4 opacity-10">&nbsp;</div>
                <hr class="d-lg-none">
                <div class="col-auto pe-3">
                    <nav>
                        <ul class="d-flex flex-column gap-2 list-unstyled small">

                            {% if object.is_active %}
                                <li><a href="{% url 'user:change_active_user' pk=object.pk %}"
                                       class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover text-danger">
                                    Деактивировать</a>
                                </li>
                            {% else %}
                                <li><a href="{% url 'user:change_active_user' pk=object.pk %}"
                                       class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover text-success">
                                    Активировать</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
    {% url 'user:login' as login_url %}
    {% url 'user:register' as register_url %}
    {% url 'user:profil' as profil_url %}


    <div class="text-center">
        {% if request.path == login_url %}
            <div>
                <h1 class="mt-4">ВХОД | <a href="{% url 'user:register' %}">РЕГИСТРАЦИЯ</a></h1>
            </div>
        {% elif request.path == register_url %}
            <div>
                <h1 class="mt-4">РЕГИСТРАЦИЯ | <a href="{% url 'user:login' %}">ВХОД</a></h1>
            </div>
        {% else %}
            <div>
                <h1 class="mt-4">ПРОФИЛЬ</h1>
            </div>
            <div class="d-flex flex-column align-items-center text-center">
                <label for="avatarUpload">
                    <img class="rounded-circle mt-5" width="150" src="/media/{{ user.avatar }}">
                </label>
                <input type="file" id="avatarUpload" style="display: none;">
            </div>
        {% endif %}
    </div>

    <div class="p-3 py-5">
        <div class="col-3 mt-2 mx-auto">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        <div class="text-danger">
                            <p>{{ field.errors }}</p>
                        </div>
                    {% endif %}
                    <br>
                {% endfor %}
                <div class="mt-2 text-center">
                    <button class="btn btn-primary profile-button" type="submit">
                        {% if request.path == login_url %}
                            Войти
                        {% elif request.path == register_url %}
                            Зарегистрироваться
                        {% else %}
                            Сохранить
                        {% endif %}
                    </button>
                </div>
                {% if form.non_field_errors %}
                    <div class="alert alert-danger mt-5 ">
                        <p>{{ form.non_field_errors }}</p>
                    </div>
                {% endif %}

                {% if request.path == login_url %}
                    <div class="mt-5 text-center">
                        <p><a href="{% url 'user:password_reset' %}"
                              class="icon-link">Забыли пароль?</a></p>
                    </div>
                {% endif %}
            </form>
        </div>

    </div>
    <script>
        const csrf_token = "{{ csrf_token }}"; // Получаем значение CSRF-токена из контекста Django
    </script>
    <script src="{% static 'js/change_avatar_script.js' %}"></script>
{% endblock %}